/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borchesaplama;

import java.text.DecimalFormat;

/**
 *
 * @author BIP
 */
public class BorcHesapla extends javax.swing.JFrame {

    /**
     * Creates new form Ders4_Kasauyg
     */
    public BorcHesapla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_borc = new javax.swing.JTextField();
        txt_odenen = new javax.swing.JTextField();
        txt_kalan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Hesapla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_borc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_borcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_borcFocusLost(evt);
            }
        });

        txt_odenen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_odenenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_odenenFocusLost(evt);
            }
        });

        txt_kalan.setEditable(false);
        txt_kalan.setBackground(new java.awt.Color(237, 236, 225));
        txt_kalan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setText("Toplam Borç");

        jLabel2.setText("Ödenen");

        jLabel3.setText("Kalan Borç");

        btn_Hesapla.setText("Hesapla");
        btn_Hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txt_borc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_odenen))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_kalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btn_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_borc, txt_kalan, txt_odenen});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_borc, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txt_odenen)
                    .addComponent(txt_kalan))
                .addGap(38, 38, 38)
                .addComponent(btn_Hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_borcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_borcFocusLost
        String tb=txt_borc.getText();
        if(!(tb.equals(""))){
            txt_borc.setText(new DecimalFormat("### TL").format(Integer.parseInt(tb)));    
        }
    }//GEN-LAST:event_txt_borcFocusLost

    private void txt_borcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_borcFocusGained
        txt_borc.setText("");
    }//GEN-LAST:event_txt_borcFocusGained

    private void txt_odenenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_odenenFocusGained
      txt_odenen.setText("");
       
    }//GEN-LAST:event_txt_odenenFocusGained

    private void txt_odenenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_odenenFocusLost
        String tb=txt_odenen.getText();
        if(!(tb.equals(""))){
            txt_odenen.setText(new DecimalFormat("### TL").format(Integer.parseInt(tb)));    
        }
    }//GEN-LAST:event_txt_odenenFocusLost

    private void btn_HesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HesaplaActionPerformed
        String tborc=txt_borc.getText();
        int b=tborc.indexOf(" ");
        String tb=tborc.substring(0, b);
        
        float  borc=Float.parseFloat(tb);
        System.out.println(borc);
        
        String o=txt_odenen.getText();
        int odi=o.indexOf(" ");
        String odenen=o.substring(0,odi);
        float odenenmiktar=Float.parseFloat(odenen);
        if(odenenmiktar>borc){
            System.out.println("Odenen miktar borçtan fazla!");
        }else{
        float kalan=borc-odenenmiktar;
        txt_kalan.setText(String.valueOf(kalan));
        
        }
        
        
    }//GEN-LAST:event_btn_HesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorcHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorcHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorcHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorcHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorcHesapla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Hesapla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_borc;
    private javax.swing.JTextField txt_kalan;
    private javax.swing.JTextField txt_odenen;
    // End of variables declaration//GEN-END:variables
}
